### ISSUE TITLE
how to use it? example is too sample and I'm noob, cant get it .

### ISSUE THREAD

**Issue by Erwin11** [ashen-sensored/sd_webui_masactrl#4]
ADJUST YOUR FOREGROUND INDEXES ACCORDING TO YOUR PROMPT, OR IT WILL NOT WORK
When your target foreground keyword is the last token in positive prompt area, corresponding token index can be found at the top right corner of positive prompt as ( * /75), ( * /150), ...

what is that meaning?

**Comment by ashen-sensored** [comment]
The foreground keyword is the character/animal/object you want to modify.

For example, the foreground keyword should be "dog" in this scenario from the paper.
![main_arch (1)](https://github.com/ashen-sensored/sd_webui_masactrl/assets/121544382/f67a1320-0b83-4bba-9442-5cdfd66002f3)

**Comment by deerox96** [comment]
If I want to change "Tiger in a desert" to "Tiger in a jungle" is the foreground keyword tiger or desert?

**Comment by ashen-sensored** [comment]
You can not change background. MasaCtrl is not able to do that

**Comment by deerox96** [comment]
Okay. Is it able to change multiple objects at once? If I want to change the red objects in a room to blue objects, can I change all of them at once by entering all of their foreground keywords?

**Comment by Erwin11** [comment]
@deerox96   thanks for reply. I read paper before,  I'm just have  a little confused.  

For example： OOO,WWW,QQQ, 1girl, XXX,BBB,YYY,CCCC,DDD, the rest of background,

I have a bundle words to describe foreground objects :1girl,  where is the location I need to pin?  
prompt as ( * /75) is  count on 1girl， or in DDD？

Here is my demo, Did I worry？

![Imgur Image](https://i.imgur.com/U07YFVN.png)

I was used the same seed  on  img2img page，
Masa Control Mode： Recon  ( I even didnt know what that is.. LOL >o<;)
Foreground Indexes :44 , I choose 1girl  


Full code is here:
```
prompt: 
(RAW photo, best quality), (realistic, photo-realistic:1.3), masterpiece, an extremely delicate and beautiful, extremely detailed, CG, unity , 2k wallpaper, Amazing, finely detail,soft light ,Fujifilm XT3
1girl, solo,(smile),:P

swimsuit, white bikini,side-tie bikini bottom, outdoors, huge breasts, navel, day, beach, looking at viewer, blue sky, ocean, cloud, water, rock, parted lips, <lora:koreanDollLikeness_v10:0.6>,(golden short hair),singing

Negative prompt: 
EasyNegative,lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,blue bikini,bad hands,

Steps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 1851503239, Face restoration: CodeFormer, Size: 512x768, Model hash: fc2511737a, Model: chilloutmix_NiPrunedFp32Fix, Denoising strength: 0.75, Clip skip: 2, ENSD: 31337
```

I just know I need to tell Masa Control where is foreground ,but I didnt know what kind of prompt she can defined？ Only  “1girl with before prompt” or just full prompt that whatever can describe 1girl all into it.  

My English is very poor, I hope my problem is explained clear . Thanks your time! Thanks your job! Good Day!😀

**Comment by ashen-sensored** [comment]
> @deerox96 thanks for reply. I read paper before, I'm just have a little confused.
> 
> For example： OOO,WWW,QQQ, 1girl, XXX,BBB,YYY,CCCC,DDD, the rest of background,
> 
> I have a bundle words to describe foreground objects :1girl, where is the location I need to pin? prompt as ( * /75) is count on 1girl， or in DDD？
> 
> Here is my demo, Did I worry？
> 
> ![Imgur Image](https://camo.githubusercontent.com/623e51d15f5fba8002aea3edb98843563791f0b9207f9b69d5358027ba29cecd/68747470733a2f2f692e696d6775722e636f6d2f5530375946564e2e706e67)
> 
> I was used the same seed on img2img page， Masa Control Mode： Recon ( I even didnt know what that is.. LOL >o<;) Foreground Indexes :44 , I choose 1girl
> 
> Full code is here:
> 
> ```
> prompt: 
> (RAW photo, best quality), (realistic, photo-realistic:1.3), masterpiece, an extremely delicate and beautiful, extremely detailed, CG, unity , 2k wallpaper, Amazing, finely detail,soft light ,Fujifilm XT3
> 1girl, solo,(smile),:P
> 
> swimsuit, white bikini,side-tie bikini bottom, outdoors, huge breasts, navel, day, beach, looking at viewer, blue sky, ocean, cloud, water, rock, parted lips, <lora:koreanDollLikeness_v10:0.6>,(golden short hair),singing
> 
> Negative prompt: 
> EasyNegative,lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,blue bikini,bad hands,
> 
> Steps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 1851503239, Face restoration: CodeFormer, Size: 512x768, Model hash: fc2511737a, Model: chilloutmix_NiPrunedFp32Fix, Denoising strength: 0.75, Clip skip: 2, ENSD: 31337
> ```
> 
> I just know I need to tell Masa Control where is foreground ,but I didnt know what kind of prompt she can defined？ Only “1girl with before prompt” or just full prompt that whatever can describe 1girl all into it.
> 
> My English is very poor, I hope my problem is explained clear . Thanks your time! Thanks your job! Good Day!grinning

Your Foreground Indexes setting is correct. However your config for XYZ graph is wrong.

For your reference,

class MasaControllerMode(enum.IntEnum):
    LOGGING = 0
    RECON = 1
    LOGRECON = 2
    IDLE = 3
    
   You should put "0,1,1,1,1" in "XYZ Graph Hooked Mode List" and click "Hook XYZ Graph" Button before you hit Generate

**Comment by Erwin11** [comment]
@ashen-sensored Thanks for your reply!~  ok, I see tags on the pictures
![Imgur Image](https://imgur.com/T9WPZro.png)

ok， I get it~ 
LOGGING = 0 
RECON = 1
LOGRECON = 2
IDLE = 3
which mode do you choose,  how many cols on XYZ graph ,  set it . Thanks~ Great job!~ happy every day~ ❤
